from pathlib import Path


# img
ROOT_DIR = Path(__file__).parent
FILES_DIR = ROOT_DIR / 'files'
WINDOW_ICON_PATH = FILES_DIR / 'calculadora.png'

# Collors
PRIMARY_COLOR = '#1E81B0'
DARKER_PRIMARY_COLOR = '#16658A'
DARKEST_PRIMARY_COLOR = '#115270'


# Sizing
BIG_FONT_SIZE = 40
MEDIUM_FONT_SIZE = 24
SMALL_FONT_SIZE = 18
TEXT_MARGIN = 15
MINIMUM_WIDTH = 500
